import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  ar: {
    // Header
    hsaGroup: "HSA GROUP",
    platformTitle: "منصة تقليل الهدر الغذائي",
    appName: "تقليل هدر الطعام",
    systemVision: "رؤية النظام",
    solutions: "الحلول",
    successStories: "قصص النجاح",
    support: "الدعم",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    contactManagement: "تواصل مع الإدارة",
    login: "تسجيل الدخول",

    // Landing Page
    trustedSolution: "حل موثوق لمجموعة هايل سعيد أنعم",
    heroTitle: "منصة تشغيل رسمية لتقليل",
    heroTitle2: "الهدر وتحويله إلى قيمة فعلية",
    heroSubtitle: "مع معايير مجموعة هايل سعيد أنعم",
    heroDescription: "واجهة واحدة تربط المصانع، المخازن، الوكلاء، والجمعيات في تجربة منسقة ومحكومة، مع بيانات متزامنة وتحليلات دقيقة لكل خطوة في سلسلة الإمداد.",
    visitDashboard: "زيارة لوحة التحكم",
    requestAccess: "طلب صلاحية جديدة",
    liveOverview: "LIVE OVERVIEW",
    dailyOperations: "العمليات اليومية",
    productionCapacity: "الطاقة الإنتاجية",
    wasteUnderMonitoring: "الهدر تحت المتابعة",
    lastUpdated: "آخر تحديث قبل 5 دقائق",
    forDonation: "4 للتبرع",
    forDisposal: "10 للتصريف",
    integrationNote: "متكامل مع Oracle, SAP, MS Dynamics، وأنظمة المصنع الداخلية لضمان بيانات موثوقة.",

    // Footer
    allRightsReserved: "جميع الحقوق محفوظة",
    technicalSupport: "الدعم التقني",
    policiesGovernance: "السياسات والحوكمة",
    trialVersion: "إصدار تجريبي",

    // Capabilities Section
    designedForAllSectors: "مصممة لكافة قطاعات المجموعة",
    governanceExperience: "تجربة رسمية تتماشى مع إجراءات الحوكمة، وتوفر محتوى مختلف لكل دور عملياتي.",
    unifiedDashboard: "لوحة تحكم موحدة",
    unifiedDashboardDesc: "رؤية لحظية للمخزون، خطوط الإنتاج، وحالات الهدر في كل المواقع.",
    governancePermissions: "حوكمة وصلاحيات",
    governancePermissionsDesc: "تجربة مخصصة لكل دور مع سياسات دقيقة للقبول والمراجعة.",
    analyticsScenarios: "تحليلات وسيناريوهات",
    analyticsScenariosDesc: "نماذج توقع تساعد الإدارة على اتخاذ قرارات استباقية وتحديد أولويات التصريف.",

    // Stories Section
    howTeamsUse: "كيف تستخدمها الفرق المختلفة؟",
    realCases: "حالات تطبيق حقيقية من مصانع ومخازن وشركاء توزيع داخل المجموعة.",
    reduceWaste28: "تخفيض الإتلاف في مصانع التعليب بنسبة 28%",
    reduceWaste28Desc: "اعتماد خطط نقل سريعة قبل انتهاء الصلاحية.",
    increaseDonations3x: "رفع نسب التبرع المنظم 3 أضعاف",
    increaseDonations3xDesc: "تنسيق فوري مع الجمعيات المعتمدة وتتبّع مسار الشحنات.",
    improveForecasting: "تحسين دقة التنبؤ بالمخزون",
    improveForecastingDesc: "دمج بيانات Oracle وMS Dynamics في نموذج موحد.",
    learnMore: "تعرف على التفاصيل",

    // Use Cases Section
    primaryAccess: "PRIMARY ACCESS",
    accessPortals: "بوابات الدخول والمهام",
    factoryWarehouse: "إدارة المصانع والمخازن",
    distributorsAgents: "الموزعون والوكلاء",
    charities: "الجهات الخيرية",
    seniorManagement: "الإدارة العليا",

    // Dashboard
    mainDashboard: "لوحة التحكم الرئيسية",
    dashboardOverview: "نظرة عامة على حالة النظام والتنبيهات المهمة",
    productsNearExpiry: "منتجات قريبة من الانتهاء",
    expiredBatches: "دفعات منتهية تحتاج إجراء",
    wasteReportsPending: "بلاغات الهدر قيد المراجعة",
    within30Days: "خلال 30 يومًا",
    urgentAction: "إجراء عاجل",
    operationalReview: "مراجعة تشغيلية",
    activeUsers: "المستخدمون النشطون",
    factoriesBranches: "المصانع والفروع",
    permissionsRoles: "صلاحيات وأدوار",

    // Login
    loginTitle: "تسجيل الدخول",
    loginDescription: "أدخل بيانات الحساب المؤسسي الممنوحة لك من قسم تقنية المعلومات",
    username: "اسم المستخدم أو البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور?",
    itSupport: "دعم تقنية المعلومات",
    enterDashboard: "دخول إلى لوحة التحكم",
    verifying: "جاري التحقق...",
    pleaseEnterCredentials: "الرجاء إدخال اسم المستخدم وكلمة المرور",
    modernInteractive: "حديثة وتفاعلية",
    back: "رجوع",

    // Header
    operationalDashboard: "لوحة تحكم تشغيلية لمجموعة هايل سعيد أنعم",
    logout: "تسجيل الخروج",
    switchToLight: "التبديل للوضع الفاتح",
    switchToDark: "التبديل للوضع الداكن",

    // Sidebar
    currentRole: "الدور الحالي",
    home: "الرئيسية",
    inventoryExpiry: "المخزون والصلاحية",
    productionWaste: "الإنتاج والهدر",
    campaignsOffers: "الحملات والعروض",
    donationsPartners: "التبرعات والشركاء",
    reportsDashboards: "التقارير ولوحات المؤشرات",
    userPermissionsManagement: "إدارة المستخدمين والصلاحيات",
    userManagement: "إدارة المستخدمين",
    adapters: "التكاملات",
    systemOverview: "نظرة عامة على النظام",

    // CommonAlerts
    productsNeedFollowup: "24 منتجًا تحتاج إلى متابعة لتصريفها قبل انتهاء الصلاحية.",
    batchesNeedDecision: "5 دفعات تحتاج قرار: تصريف خاص، إتلاف نظامي، أو تحويل للتبرع.",
    reportsAwaitingApproval: "3 بلاغات من خطوط الإنتاج بانتظار اعتماد مدير المصنع.",

    // AdminCards
    systemPermissions: "نظام وصلاحيات",
    operationalSites: "مواقع تشغيلية",
    organizationalStructures: "هياكل تنظيمية",

    // New Pages
    refrigerationManagement: "إدارة الأصول والثلاجات",
    aiDashboard: "محرك AI والتنبؤات",
    digitalTwin: "التوأم الرقمي",
    productionPlanning: "تخطيط الإنتاج",
    productionManagement: "إدارة الإنتاج",
    batchManagement: "إدارة الدفعات",
    fifoList: "قائمة FIFO",
    fefoList: "قائمة FEFO",
    fifoDescription: "FIFO (First In First Out): الدفعات مرتبة حسب تاريخ الإنشاء (الأقدم أولاً)",
    fefoDescription: "FEFO (First Expire First Out): الدفعات مرتبة حسب تاريخ الانتهاء (الأقرب للانتهاء أولاً)",
    allBatches: "جميع الدفعات",
    priority: "الأولوية",
    daysUntilExpiry: "أيام حتى الانتهاء",
    days: "يوم",
    distributionManagement: "إدارة التوزيع",
    fleetTracking: "تتبع المركبات",
    wasteAnalysis: "تحليل الهدر",
    shipmentManagement: "إدارة الشحنات",
    orderManagement: "إدارة الطلبات",
    returnsManagement: "إدارة المرتجعات",
    charityIntegration: "ربط الجمعيات الخيرية",
    qualityManagement: "إدارة الجودة",
    alertCenter: "مركز التنبيهات",
    reports: "التقارير",
    heatMaps: "خرائط الحرارة",
    heatMapsDescription: "عرض مرئي لدرجات الحرارة والرطوبة في جميع المنشآت",
    rfidTracking: "تتبع RFID",
    rfidTrackingDescription: "تتبع ومراقبة جميع علامات RFID في الوقت الفعلي",
    auditLogs: "سجلات التدقيق",
    auditLogsDescription: "عرض جميع سجلات الأنشطة والعمليات في النظام",
    taskManagement: "إدارة المهام",
    taskManagementDescription: "إدارة وتتبع مهامك",
    leadManagement: "إدارة العملاء المحتملين",
    leadManagementDescription: "إدارة وتتبع عملاءك المحتملين",
    createLead: "إنشاء عميل محتمل",
    editLead: "تعديل عميل محتمل",
    searchLeads: "بحث في العملاء المحتملين...",
    noLeadsFound: "لم يتم العثور على عملاء محتملين",
    company: "الشركة",
    source: "المصدر",
    value: "القيمة",
    probability: "الاحتمالية",
    nextFollowup: "المتابعة القادمة",
    recordContact: "تسجيل اتصال",
    won: "فاز",
    lost: "خسر",
    contacted: "تم الاتصال",
    qualified: "مؤهل",
    proposal: "عرض",
    negotiation: "تفاوض",
    website: "الموقع الإلكتروني",
    referral: "إحالة",
    coldCall: "اتصال بارد",
    event: "حدث",
    allSources: "جميع المصادر",
    totalValue: "القيمة الإجمالية",
    chatbot: "المساعد الذكي",
    chatbotDescription: "اسألني أي شيء عن النظام",
    chatbotWelcome: "مرحباً! أنا هنا لمساعدتك في نظام تقليل الهدر الغذائي. كيف يمكنني مساعدتك اليوم؟",
    chatbotPlaceholder: "اكتب رسالتك...",
    chatbotError: "عذراً، حدث خطأ. يرجى المحاولة مرة أخرى.",
    send: "إرسال",
    clear: "مسح",
    createTask: "إنشاء مهمة",
    editTask: "تعديل مهمة",
    searchTasks: "بحث في المهام...",
    allStatuses: "جميع الحالات",
    allPriorities: "جميع الأولويات",
    today: "اليوم",
    thisWeek: "هذا الأسبوع",
    inProgress: "قيد التنفيذ",
    completed: "مكتمل",
    cancelled: "ملغي",
    overdue: "متأخر",
    dueDate: "تاريخ الاستحقاق",
    category: "الفئة",
    assignTo: "تعيين إلى",
    selectUser: "اختر مستخدم",
    noTasksFound: "لم يتم العثور على مهام",
    confirmDelete: "هل أنت متأكد من حذف هذه المهمة؟",
    update: "تحديث",
    exportExcel: "تصدير Excel",
    exportExcelDescription: "تصدير التقرير كملف Excel",
    adapterManagement: "إدارة التكاملات",
    adapterManagementDescription: "إدارة التكاملات مع الأنظمة الخارجية",
    createAdapter: "إنشاء تكامل",
    adapterName: "اسم التكامل",
    adapterType: "نوع التكامل",
    adapterId: "معرف التكامل",
    configuration: "الإعدادات",
    test: "اختبار",
    enable: "تفعيل",
    disable: "تعطيل",
    connectionSuccessful: "تم الاتصال بنجاح",
    connectionFailed: "فشل الاتصال",
    noAdapters: "لا توجد تكاملات م configured",
    lastConnection: "آخر اتصال",
    never: "أبداً",
    branchesManagement: "إدارة الفروع",

    // Production Management Page
    manageProductionBatches: "إدارة دفعات الإنتاج وتتبع الهدر",
    totalBatches: "إجمالي الدفعات",
    totalQuantity: "إجمالي الكمية",
    totalWaste: "إجمالي الهدر",
    wasteEvents: "أحداث الهدر",
    allStatuses: "جميع الحالات",
    searchBatches: "بحث في الدفعات...",
    recordWaste: "تسجيل هدر",
    noBatchesFound: "لم يتم العثور على دفعات",
    batchCode: "رمز الدفعة",
    product: "المنتج",
    productId: "معرف المنتج",
    productionDate: "تاريخ الإنتاج",
    expiryDate: "تاريخ انتهاء الصلاحية",
    create: "إنشاء",
    quantity: "الكمية",
    facility: "المنشأة",
    shelfLife: "مدة الصلاحية",
    status: "الحالة",
    actions: "الإجراءات",
    inStorage: "في المخزن",
    inTransit: "قيد النقل",
    soldOut: "نفدت",
    wasted: "مهدر",
    loading: "جاري التحميل...",
    selectBatch: "اختر الدفعة",
    change: "تغيير",
    wasteQuantity: "كمية الهدر",
    enterQuantity: "أدخل الكمية",
    unit: "وحدة",
    kg: "حبة",
    g: "جرام",
    liter: "لتر",
    ml: "مل",
    availableQuantity: "الكمية المتاحة",
    wasteReason: "سبب الهدر",
    enterReason: "أدخل سبب الهدر",
    wasteCost: "تكلفة الهدر",
    optional: "اختياري",
    enterCost: "أدخل التكلفة",
    recording: "جاري التسجيل...",
    record: "تسجيل",
    cancel: "إلغاء",
    createBatch: "إنشاء دفعة جديدة",
    enterBatchCode: "أدخل رمز الدفعة",
    enterProductId: "أدخل معرف المنتج",
    productIdHint: "يجب أن يكون المنتج موجوداً في النظام",
    expiryDateHint: "يجب أن يكون بعد تاريخ الإنتاج",
    creating: "جاري الإنشاء...",
    view: "عرض",
    facilitiesManagement: "إدارة المرافق",
    vehiclesManagement: "إدارة المركبات",
    supermarketsManagement: "إدارة السوبر ماركت",
    alertSettings: "إعدادات التنبيهات",
    systemSettings: "إعدادات النظام",
    demandForecast: "توقع الطلب",
    inventory: "المخزون",
    inventoryManagement: "إدارة المخازن",
    sales: "المبيعات",
    trackShipment: "تتبع الشحنة",
    batches: "الدفعات",
    // Location Types
    warehouse: "المستودع",
    cold_storage: "التخزين البارد",
    distribution_center: "مركز التوزيع",
    factory: "المصنع",
    store: "المتجر",
    supermarket: "السوبرماركت",
    branch: "الفرع",
    retail: "التجزئة",
    company_vehicle: "شاحنة الشركة",
    distributor_vehicle: "شاحنة الموزع",
    company_warehouse: "مستودع الشركة",
    distributor_warehouse: "مستودع الموزع",
    point_of_sale: "نقطة البيع",
    vehicle: "المركبة",
    truck: "الشاحنة",
    unknown: "غير محدد",

    // Distribution Management
    manageOrderDistribution: "إدارة توزيع الطلبات وتحسين المسارات",
    searchOrders: "بحث في الطلبات...",
    optimizeRoute: "تحسين المسار",
    optimizing: "جاري التحسين...",
    orderNumber: "رقم الطلب",
    orderDate: "تاريخ الطلب",
    priority: "الأولوية",
    noOrdersFound: "لم يتم العثور على طلبات",
    orderDistributed: "تم توزيع الطلب بنجاح",
    selectOrders: "يرجى اختيار طلبات لتحسين المسار",
    routeOptimized: "تم تحسين المسار بنجاح",
    distribute: "توزيع",
    distributing: "جاري التوزيع...",
    auto: "تلقائي",
    direct: "مباشر",
    aggregated: "مجمع",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    shipped: "تم الشحن",
    delivered: "تم التسليم",

    // Shipment Management
    createAndTrackShipments: "إنشاء وتتبع الشحنات مع فحص AI للمخاطر",
    createNewShipment: "إنشاء شحنة جديدة",
    shipmentNumber: "رقم الشحنة",
    fromFacility: "من المنشأة",
    toFacility: "إلى المنشأة",
    driver: "السائق",
    noShipmentsFound: "لم يتم العثور على شحنات",
    createShipment: "إنشاء شحنة",
    checking: "جاري الفحص...",
    checkDelivery: "فحص التسليم",
    pleaseLogin: "يرجى تسجيل الدخول لعرض الشحنات",
    // VPS Categories
    vps_Beverages_Non_Perishable: "مشروبات غير قابلة للتلف",
    vps_Dairy_and_Eggs: "ألبان وبيض",
    vps_Frozen_Foods: "أغذية مجمدة",
    vps_Fruits_and_Vegetables: "فواكه وخضروات",
    vps_Meat_and_Poultry: "لحوم ودواجن",
    vps_Packaged_Foods: "أغذية معلبة",
  },
  en: {
    // Header
    hsaGroup: "HSA GROUP",
    platformTitle: "Food Waste Reduction Platform",
    appName: "Food Waste Reduction",
    systemVision: "System Vision",
    solutions: "Solutions",
    successStories: "Success Stories",
    support: "Support",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    contactManagement: "Contact Management",
    login: "Login",

    // Landing Page
    trustedSolution: "Trusted solution for Hayel Saeed Anam Group",
    heroTitle: "Official operating platform to reduce",
    heroTitle2: "waste and convert it into actual value",
    heroSubtitle: "with Hayel Saeed Anam Group standards",
    heroDescription: "A single interface connecting factories, warehouses, agents, and associations in a coordinated and controlled experience, with synchronized data and accurate analytics for every step in the supply chain.",
    visitDashboard: "Visit Control Panel",
    requestAccess: "Request New Authorization",
    liveOverview: "LIVE OVERVIEW",
    dailyOperations: "Daily Operations",
    productionCapacity: "Production Capacity",
    wasteUnderMonitoring: "Waste under monitoring",
    lastUpdated: "Last updated 5 minutes ago",
    forDonation: "4 for donation",
    forDisposal: "10 for disposal",
    integrationNote: "Integrated with Oracle, SAP, MS Dynamics, and internal factory systems to ensure reliable data.",

    // Footer
    allRightsReserved: "All rights reserved",
    technicalSupport: "Technical Support",
    policiesGovernance: "Policies and Governance",
    trialVersion: "Trial Version",

    // Capabilities Section
    designedForAllSectors: "Designed for all sectors of the group",
    governanceExperience: "A formal experience that aligns with governance procedures and provides different content for each operational role.",
    unifiedDashboard: "Unified Control Panel",
    unifiedDashboardDesc: "Real-time visibility of inventory, production lines, and waste situations across all locations.",
    governancePermissions: "Governance and Authorizations",
    governancePermissionsDesc: "A customized experience for each role with precise policies for approval and review.",
    analyticsScenarios: "Analytics and Scenarios",
    analyticsScenariosDesc: "Forecasting models that help management make proactive decisions and determine disposal priorities.",

    // Stories Section
    howTeamsUse: "How do different teams use it?",
    realCases: "Real application cases from factories, warehouses, and distribution partners within the group.",
    reduceWaste28: "28% reduction in spoilage in canning factories",
    reduceWaste28Desc: "Adopting rapid transfer plans before expiration.",
    increaseDonations3x: "3x increase in organized donation rates",
    increaseDonations3xDesc: "Immediate coordination with accredited charities and tracking shipment routes.",
    improveForecasting: "Improve inventory forecasting accuracy",
    improveForecastingDesc: "Integrating data in a unified model from MS Dynamics and Oracle.",
    learnMore: "Learn more",

    // Use Cases Section
    primaryAccess: "PRIMARY ACCESS",
    accessPortals: "Access Portals and Tasks",
    factoryWarehouse: "Factory and Warehouse Management",
    distributorsAgents: "Distributors and Agents",
    charities: "Charitable Organizations",
    seniorManagement: "Senior Management",

    // Dashboard
    mainDashboard: "Main Dashboard",
    dashboardOverview: "Overview of system status and important alerts",
    productsNearExpiry: "Products near expiry",
    expiredBatches: "Expired batches need action",
    wasteReportsPending: "Waste reports under review",
    within30Days: "Within 30 days",
    urgentAction: "Urgent action",
    operationalReview: "Operational review",
    activeUsers: "Active Users",
    factoriesBranches: "Factories and Branches",
    permissionsRoles: "Permissions and Roles",

    // Login
    loginTitle: "Login",
    loginDescription: "Enter your institutional account credentials provided by the IT department",
    username: "Username or Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    itSupport: "IT Support",
    enterDashboard: "Enter Dashboard",
    verifying: "Verifying...",
    pleaseEnterCredentials: "Please enter username and password",
    back: "Back",
    modernInteractive: "modern and interactive",

    // Header
    operationalDashboard: "Operational dashboard for Hayel Saeed Anam Group",
    logout: "Logout",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",

    // Sidebar
    currentRole: "Current Role",
    home: "Home",
    inventoryExpiry: "Inventory & Expiry",
    productionWaste: "Production & Waste",
    campaignsOffers: "Campaigns & Offers",
    donationsPartners: "Donations & Partners",
    reportsDashboards: "Reports & Dashboards",
    userPermissionsManagement: "User & Permissions Management",
    systemOverview: "System Overview",

    // CommonAlerts
    productsNeedFollowup: "24 products need follow-up to be disposed before expiry.",
    batchesNeedDecision: "5 batches need decision: special disposal, systematic destruction, or donation transfer.",
    reportsAwaitingApproval: "3 reports from production lines awaiting factory manager approval.",

    // AdminCards
    systemPermissions: "System & Permissions",
    operationalSites: "Operational Sites",
    organizationalStructures: "Organizational Structures",

    // New Pages
    refrigerationManagement: "Asset & Refrigeration Management",
    aiDashboard: "AI Engine & Predictions",
    digitalTwin: "Digital Twin",
    productionPlanning: "Production Planning",
    productionManagement: "Production Management",
    batchManagement: "Batch Management",
    distributionManagement: "Distribution Management",
    fleetTracking: "Fleet Tracking",
    wasteAnalysis: "Waste Analysis",
    shipmentManagement: "Shipment Management",
    orderManagement: "Order Management",
    returnsManagement: "Returns Management",
    charityIntegration: "Charity Integration",
    qualityManagement: "Quality Management",
    alertCenter: "Alert Center",
    reports: "Reports",
    heatMaps: "Heat Maps",
    heatMapsDescription: "Visual representation of temperature and humidity across all facilities",
    rfidTracking: "RFID Tracking",
    rfidTrackingDescription: "Real-time tracking and monitoring of all RFID tags",
    branchesManagement: "Branches Management",

    // Production Management Page
    manageProductionBatches: "Manage production batches and track waste",
    totalBatches: "Total Batches",
    totalQuantity: "Total Quantity",
    totalWaste: "Total Waste",
    wasteEvents: "Waste Events",
    allStatuses: "All Statuses",
    searchBatches: "Search batches...",
    recordWaste: "Record Waste",
    noBatchesFound: "No batches found",
    batchCode: "Batch Code",
    product: "Product",
    productId: "Product ID",
    productionDate: "Production Date",
    expiryDate: "Expiry Date",
    create: "Create",
    quantity: "Quantity",
    facility: "Facility",
    shelfLife: "Shelf Life",
    status: "Status",
    actions: "Actions",
    inStorage: "In Storage",
    inTransit: "In Transit",
    soldOut: "Sold Out",
    wasted: "Wasted",
    loading: "Loading...",
    selectBatch: "Select Batch",
    change: "Change",
    wasteQuantity: "Waste Quantity",
    enterQuantity: "Enter quantity",
    unit: "Unit",
    kg: "kg",
    g: "g",
    liter: "Liter",
    ml: "ml",
    availableQuantity: "Available Quantity",
    wasteReason: "Waste Reason",
    enterReason: "Enter waste reason",
    wasteCost: "Waste Cost",
    optional: "Optional",
    enterCost: "Enter cost",
    recording: "Recording...",
    record: "Record",
    cancel: "Cancel",
    createBatch: "Create New Batch",
    enterBatchCode: "Enter batch code",
    enterProductId: "Enter product ID",
    productIdHint: "Product must exist in the system",
    expiryDateHint: "Must be after production date",
    creating: "Creating...",
    view: "View",
    facilitiesManagement: "Facilities Management",
    fifoList: "FIFO List",
    fefoList: "FEFO List",
    fifoDescription: "FIFO (First In First Out): Batches ordered by creation date (oldest first)",
    fefoDescription: "FEFO (First Expire First Out): Batches ordered by expiry date (earliest expiry first)",
    allBatches: "All Batches",
    priority: "Priority",
    daysUntilExpiry: "Days Until Expiry",
    days: "days",
    exportExcel: "Export Excel",
    exportExcelDescription: "Export report as Excel file",
    vehiclesManagement: "Vehicles Management",
    supermarketsManagement: "Supermarkets Management",
    alertSettings: "Alert Settings",
    systemSettings: "System Settings",
    auditLogs: "Audit Logs",
    auditLogsDescription: "View all activity and operation logs in the system",
    taskManagement: "Task Management",
    taskManagementDescription: "Manage and track your tasks",
    leadManagement: "Lead Management",
    leadManagementDescription: "Manage and track your sales leads",
    createLead: "Create Lead",
    editLead: "Edit Lead",
    searchLeads: "Search leads...",
    noLeadsFound: "No leads found",
    company: "Company",
    source: "Source",
    value: "Value",
    probability: "Probability",
    nextFollowup: "Next Follow-up",
    recordContact: "Record Contact",
    won: "Won",
    lost: "Lost",
    contacted: "Contacted",
    qualified: "Qualified",
    proposal: "Proposal",
    negotiation: "Negotiation",
    website: "Website",
    referral: "Referral",
    coldCall: "Cold Call",
    event: "Event",
    allSources: "All Sources",
    totalValue: "Total Value",
    chatbot: "Chatbot Assistant",
    chatbotDescription: "Ask me anything about the system",
    chatbotWelcome: "Hello! I'm here to help you with the Food Waste Reduction System. How can I assist you today?",
    chatbotPlaceholder: "Type your message...",
    chatbotError: "Sorry, I encountered an error. Please try again.",
    send: "Send",
    clear: "Clear",
    exportExcel: "Export Excel",
    exportExcelDescription: "Export report as Excel file",
    demandForecast: "Demand Forecast",
    inventory: "Inventory",
    inventoryManagement: "Inventory Management",
    sales: "Sales",
    trackShipment: "Track Shipment",
    batches: "Batches",
    // Location Types
    warehouse: "Warehouse",
    cold_storage: "Cold Storage",
    distribution_center: "Distribution Center",
    factory: "Factory",
    store: "Store",
    supermarket: "Supermarket",
    branch: "Branch",
    retail: "Retail",
    company_vehicle: "Company Vehicle",
    distributor_vehicle: "Distributor Vehicle",
    company_warehouse: "Company Warehouse",
    distributor_warehouse: "Distributor Warehouse",
    point_of_sale: "Point of Sale",
    vehicle: "Vehicle",
    truck: "Truck",
    unknown: "Unknown",

    // Distribution Management
    manageOrderDistribution: "Manage order distribution and route optimization",
    searchOrders: "Search orders...",
    optimizeRoute: "Optimize Route",
    optimizing: "Optimizing...",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    priority: "Priority",
    noOrdersFound: "No orders found",
    orderDistributed: "Order distributed successfully",
    selectOrders: "Please select orders to optimize route",
    routeOptimized: "Route optimized successfully",
    distribute: "Distribute",
    distributing: "Distributing...",
    auto: "Auto",
    direct: "Direct",
    aggregated: "Aggregated",
    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",

    // Shipment Management
    createAndTrackShipments: "Create and track shipments with AI risk assessment",
    createNewShipment: "Create New Shipment",
    shipmentNumber: "Shipment Number",
    fromFacility: "From Facility",
    toFacility: "To Facility",
    driver: "Driver",
    noShipmentsFound: "No shipments found",
    createShipment: "Create Shipment",
    checking: "Checking...",
    checkDelivery: "Check Delivery",
    pleaseLogin: "Please login to view shipments",
    // VPS Categories
    vps_Beverages_Non_Perishable: "Non-Perishable Beverages",
    vps_Dairy_and_Eggs: "Dairy and Eggs",
    vps_Frozen_Foods: "Frozen Foods",
    vps_Fruits_and_Vegetables: "Fruits and Vegetables",
    vps_Meat_and_Poultry: "Meat and Poultry",
    vps_Packaged_Foods: "Packaged Foods",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const saved = localStorage.getItem("language");
        return saved || "ar";
      }
    } catch (e) {
      console.warn('localStorage not available:', e);
    }
    return "ar";
  });

  useEffect(() => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem("language", language);
      }
      if (typeof document !== 'undefined') {
        document.documentElement.setAttribute("dir", language === "ar" ? "rtl" : "ltr");
        document.documentElement.setAttribute("lang", language);
      }
    } catch (e) {
      console.warn('Error setting language:', e);
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "ar" ? "en" : "ar"));
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

