// بيانات وهمية شاملة للنظام

// بيانات الثلاجات
export const refrigerators = [
  {
    id: "FZ-01",
    name: "ثلاجة المخزن الرئيسي 1",
    location: "مخزن صنعاء الرئيسي",
    currentTemp: 4.2,
    normalRange: { min: 4, max: 6 },
    lastDoorOpen: "قبل 15 دقيقة",
    energyConsumption: 2.3,
    normalEnergy: 2.0,
    status: "ممتاز",
    humidity: 65,
    doorOpensToday: 12,
    age: 3,
    lastMaintenance: "2024-11-15",
    failureRisk: 5,
    failureRiskDays: null,
    predictedFailureType: "None",
    predictionConfidence: 0.95,
  },
  {
    id: "FZ-02",
    name: "ثلاجة المخزن الرئيسي 2",
    location: "مخزن صنعاء الرئيسي",
    currentTemp: 5.1,
    normalRange: { min: 4, max: 6 },
    lastDoorOpen: "قبل 8 دقائق",
    energyConsumption: 2.1,
    normalEnergy: 2.0,
    status: "طبيعي",
    humidity: 68,
    doorOpensToday: 18,
    age: 2,
    lastMaintenance: "2024-12-01",
    failureRisk: 8,
    failureRiskDays: null,
    predictedFailureType: "None",
    predictionConfidence: 0.92,
  },
  {
    id: "FZ-14",
    name: "ثلاجة مخزن تعز",
    location: "مخزن تعز",
    currentTemp: 9.2,
    normalRange: { min: 4, max: 6 },
    lastDoorOpen: "قبل 2 دقيقة",
    energyConsumption: 3.8,
    normalEnergy: 2.0,
    status: "خطر",
    humidity: 75,
    doorOpensToday: 45,
    age: 5,
    lastMaintenance: "2024-09-20",
    failureRisk: 85,
    failureRiskDays: 10,
    predictedFailureType: "Compressor",
    predictionConfidence: 0.88,
  },
  {
    id: "FZ-09",
    name: "ثلاجة مخزن عدن",
    location: "مخزن عدن",
    currentTemp: 5.0,
    normalRange: { min: 4, max: 6 },
    lastDoorOpen: "قبل 10 دقائق",
    energyConsumption: 2.0,
    normalEnergy: 2.0,
    status: "ممتاز",
    humidity: 62,
    doorOpensToday: 8,
    age: 1,
    lastMaintenance: "2024-12-10",
    failureRisk: 3,
    failureRiskDays: null,
    predictedFailureType: "None",
    predictionConfidence: 0.98,
  },
  {
    id: "FZ-15",
    name: "ثلاجة مخزن إب",
    location: "مخزن إب",
    currentTemp: 7.5,
    normalRange: { min: 4, max: 6 },
    lastDoorOpen: "قبل 5 دقائق",
    energyConsumption: 3.2,
    normalEnergy: 2.0,
    status: "تحذير",
    humidity: 70,
    doorOpensToday: 25,
    age: 4,
    lastMaintenance: "2024-10-15",
    failureRisk: 45,
    failureRiskDays: 25,
    predictedFailureType: "Thermostat",
    predictionConfidence: 0.75,
  },
];

// بيانات المنتجات والدفعات
export const batches = [
  {
    id: "BATCH-001",
    productName: "لبن شامي",
    productType: "ألبان",
    productionDate: "2024-11-01",
    expiryDate: "2024-12-15",
    actualExpiryDate: "2024-12-18",
    quantity: 500,
    unit: "علبة",
    location: "مخزن صنعاء الرئيسي",
    refrigerator: "FZ-01",
    currentTemp: 4.2,
    humidity: 65,
    spoilageRisk: 12,
    remainingLife: 35,
    status: "آمن",
    governorate: "صنعاء",
  },
  {
    id: "BATCH-002",
    productName: "عصير برتقال",
    productType: "عصائر",
    productionDate: "2024-10-15",
    expiryDate: "2025-01-15",
    actualExpiryDate: "2025-01-10",
    quantity: 1200,
    unit: "زجاجة",
    location: "مخزن تعز",
    refrigerator: "FZ-14",
    currentTemp: 9.2,
    humidity: 75,
    spoilageRisk: 78,
    remainingLife: 15,
    status: "خطر",
    governorate: "تعز",
  },
  {
    id: "BATCH-003",
    productName: "جبنة بيضاء",
    productType: "ألبان",
    productionDate: "2024-12-01",
    expiryDate: "2024-12-20",
    actualExpiryDate: "2024-12-22",
    quantity: 300,
    unit: "كيلو",
    location: "مخزن عدن",
    refrigerator: "FZ-09",
    currentTemp: 5.0,
    humidity: 62,
    spoilageRisk: 8,
    remainingLife: 18,
    status: "آمن",
    governorate: "عدن",
  },
];

// بيانات المركبات
export const vehicles = [
  {
    id: "V-12",
    plateNumber: "صنعاء 1234",
    type: "شاحنة تبريد",
    vfs: 85,
    status: "جيدة",
    age: 2,
    lastMaintenance: "2024-11-20",
    totalTrips: 145,
    damagedProductsRate: 2.1,
    avgTemp: 4.5,
    coolingStops: 3,
    avgVibration: 2.3,
    currentLocation: "صنعاء",
    coordinates: { lat: 15.3694, lng: 44.191 },
    currentTrip: null,
    driver: "أحمد محمد",
    speed: 0,
    fuelLevel: 85,
  },
  {
    id: "V-03",
    plateNumber: "تعز 5678",
    type: "شاحنة تبريد",
    vfs: 45,
    status: "ضعيفة",
    age: 8,
    lastMaintenance: "2024-08-15",
    totalTrips: 320,
    damagedProductsRate: 12.5,
    avgTemp: 8.2,
    coolingStops: 15,
    avgVibration: 5.8,
    currentLocation: "طريق صنعاء-إب",
    coordinates: { lat: 14.2000, lng: 44.1000 },
    route: [
      { lat: 13.5779, lng: 44.017 }, // تعز
      { lat: 13.8000, lng: 44.0500 },
      { lat: 14.0000, lng: 44.0800 },
      { lat: 14.2000, lng: 44.1000 }, // الموقع الحالي
      { lat: 14.4000, lng: 44.1200 },
      { lat: 13.9667, lng: 44.1667 }, // إب
    ],
    direction: 45, // درجة الاتجاه
    currentTrip: {
      from: "مخزن تعز",
      to: "فرع إب",
      product: "عصير برتقال",
      startTime: "2025-01-16T08:00:00",
      estimatedArrival: "2025-01-16T12:00:00",
      currentTemp: 7.5,
      progress: 45,
      distanceRemaining: 120,
      fromCoordinates: { lat: 13.5779, lng: 44.017 },
      toCoordinates: { lat: 13.9667, lng: 44.1667 },
      failurePoint: 0.65, // 65% من المسار
    },
    predictedFailureType: "Temperature Breach",
    predictionConfidence: 0.75,
    driver: "محمد علي",
    speed: 65,
    fuelLevel: 60,
  },
  {
    id: "V-25",
    plateNumber: "عدن 9012",
    type: "شاحنة تبريد",
    vfs: 92,
    status: "ممتازة",
    age: 1,
    lastMaintenance: "2024-12-01",
    totalTrips: 45,
    damagedProductsRate: 0.5,
    avgTemp: 3.8,
    coolingStops: 1,
    avgVibration: 1.2,
    currentLocation: "عدن",
    coordinates: { lat: 12.7855, lng: 45.0187 },
    currentTrip: null,
    driver: "خالد أحمد",
    speed: 0,
    fuelLevel: 95,
  },
  {
    id: "V-08",
    plateNumber: "صنعاء 3456",
    type: "شاحنة تبريد",
    vfs: 78,
    status: "جيدة",
    age: 3,
    lastMaintenance: "2024-10-10",
    totalTrips: 210,
    damagedProductsRate: 3.2,
    avgTemp: 5.1,
    coolingStops: 5,
    avgVibration: 3.1,
    currentLocation: "طريق صنعاء-الحديدة",
    coordinates: { lat: 15.1000, lng: 43.5000 },
    route: [
      { lat: 15.3694, lng: 44.191 }, // صنعاء
      { lat: 15.3000, lng: 44.0000 },
      { lat: 15.2000, lng: 43.8000 },
      { lat: 15.1000, lng: 43.5000 }, // الموقع الحالي
      { lat: 15.0500, lng: 43.3000 },
      { lat: 15.0500, lng: 42.6000 }, // الحديدة
    ],
    direction: 270, // درجة الاتجاه (غرب)
    currentTrip: {
      from: "مخزن صنعاء الرئيسي",
      to: "فرع الحديدة",
      product: "لبن شامي",
      startTime: "2025-01-16T06:00:00",
      estimatedArrival: "2025-01-16T10:00:00",
      currentTemp: 4.8,
      progress: 70,
      distanceRemaining: 60,
      fromCoordinates: { lat: 15.3694, lng: 44.191 },
      toCoordinates: { lat: 15.0500, lng: 42.6000 },
    },
    driver: "يوسف حسن",
    speed: 70,
    fuelLevel: 45,
  },
  {
    id: "V-15",
    plateNumber: "تعز 7890",
    type: "شاحنة تبريد",
    vfs: 65,
    status: "متوسطة",
    age: 5,
    lastMaintenance: "2024-09-25",
    totalTrips: 280,
    damagedProductsRate: 5.8,
    avgTemp: 6.2,
    coolingStops: 8,
    avgVibration: 4.2,
    currentLocation: "تعز",
    coordinates: { lat: 13.5779, lng: 44.017 },
    currentTrip: null,
    driver: "علي سعيد",
    speed: 0,
    fuelLevel: 75,
  },
];

// بيانات المواقع
export const locations = [
  {
    id: "LOC-001",
    name: "مخزن صنعاء الرئيسي",
    type: "مخزن",
    governorate: "صنعاء",
    coordinates: { lat: 15.3694, lng: 44.191 },
    status: "ممتاز",
    refrigerators: ["FZ-01", "FZ-02"],
    batches: ["BATCH-001"],
  },
  {
    id: "LOC-002",
    name: "مخزن تعز",
    type: "مخزن",
    governorate: "تعز",
    coordinates: { lat: 13.5779, lng: 44.017 },
    status: "خطر",
    refrigerators: ["FZ-14"],
    batches: ["BATCH-002"],
  },
  {
    id: "LOC-003",
    name: "مخزن عدن",
    type: "مخزن",
    governorate: "عدن",
    coordinates: { lat: 12.7855, lng: 45.0187 },
    status: "ممتاز",
    refrigerators: ["FZ-09"],
    batches: ["BATCH-003"],
  },
  {
    id: "LOC-004",
    name: "مصنع الألبان",
    type: "مصنع",
    governorate: "صنعاء",
    coordinates: { lat: 15.4, lng: 44.2 },
    status: "طبيعي",
    refrigerators: [],
    batches: [],
  },
  {
    id: "LOC-005",
    name: "فرع إب",
    type: "فرع",
    governorate: "إب",
    coordinates: { lat: 13.9667, lng: 44.1667 },
    status: "طبيعي",
    refrigerators: [],
    batches: [],
  },
];

// بيانات التنبؤات AI
export const aiPredictions = {
  demandForecast: [
    {
      governorate: "صنعاء",
      product: "لبن شامي",
      predictedDemand: 850,
      confidence: 0.92,
      period: "الأسبوع القادم",
    },
    {
      governorate: "تعز",
      product: "عصير برتقال",
      predictedDemand: 620,
      confidence: 0.88,
      period: "الأسبوع القادم",
    },
    {
      governorate: "عدن",
      product: "جبنة بيضاء",
      predictedDemand: 450,
      confidence: 0.85,
      period: "الأسبوع القادم",
    },
    {
      governorate: "إب",
      product: "لبن شامي",
      predictedDemand: 380,
      confidence: 0.87,
      period: "الأسبوع القادم",
    },
    {
      governorate: "المكلا",
      product: "عصير برتقال",
      predictedDemand: 290,
      confidence: 0.83,
      period: "الأسبوع القادم",
    },
  ],
  spoilagePredictions: [
    {
      batchId: "BATCH-001",
      productName: "لبن شامي",
      spoilageRisk: 12,
      riskLevel: "منخفض",
      factors: ["حرارة مناسبة", "رطوبة طبيعية"],
    },
    {
      batchId: "BATCH-002",
      productName: "عصير برتقال",
      spoilageRisk: 78,
      riskLevel: "عالي",
      factors: ["حرارة مرتفعة", "رطوبة عالية", "ثلاجة معطلة"],
    },
    {
      batchId: "BATCH-003",
      productName: "جبنة بيضاء",
      spoilageRisk: 8,
      riskLevel: "منخفض",
      factors: ["حرارة مناسبة"],
    },
  ],
  expiryPredictions: [
    {
      batchId: "BATCH-001",
      productName: "لبن شامي",
      writtenExpiry: "2024-12-15",
      predictedExpiry: "2024-12-18",
      difference: 3,
      reason: "ظروف تخزين جيدة",
    },
    {
      batchId: "BATCH-002",
      productName: "عصير برتقال",
      writtenExpiry: "2025-01-15",
      predictedExpiry: "2025-01-10",
      difference: -5,
      reason: "حرارة مرتفعة في التخزين",
    },
  ],
};

// بيانات تحليل الهدر
// بيانات تحليل الهدر (لنموذج Root Cause Classification)
export const wasteAnalysisData = [
  {
    id: "WASTE-001",
    product: "عصير برتقال",
    batchId: "BATCH-001",
    wasteAmount: 150,
    date: "2024-12-15",
    location: "مخزن تعز",
    rootCause: "Storage",
    confidence: 0.85,
  },
  {
    id: "WASTE-002",
    product: "لبن شامي",
    batchId: "BATCH-002",
    wasteAmount: 80,
    date: "2024-12-14",
    location: "مخزن صنعاء",
    rootCause: "Transport",
    confidence: 0.72,
  },
  {
    id: "WASTE-003",
    product: "دقيق",
    batchId: "BATCH-003",
    wasteAmount: 200,
    date: "2024-12-13",
    location: "مخزن عدن",
    rootCause: "Overproduction",
    confidence: 0.90,
  },
  {
    id: "WASTE-004",
    product: "سمن",
    batchId: "BATCH-004",
    wasteAmount: 95,
    date: "2024-12-12",
    location: "مخزن تعز",
    rootCause: "Expiry",
    confidence: 0.78,
  },
  {
    id: "WASTE-005",
    product: "زيت طبخ",
    batchId: "BATCH-005",
    wasteAmount: 120,
    date: "2024-12-11",
    location: "مخزن صنعاء",
    rootCause: "Damage",
    confidence: 0.82,
  },
  {
    id: "WASTE-006",
    product: "معجون طماطم",
    batchId: "BATCH-006",
    wasteAmount: 65,
    date: "2024-12-10",
    location: "مخزن عدن",
    rootCause: "Storage",
    confidence: 0.75,
  },
];

export const wasteAnalysis = {
  rootCauses: [
    { cause: "سوء التخزين", percentage: 35, count: 45 },
    { cause: "انتهاء الصلاحية", percentage: 28, count: 36 },
    { cause: "نقل سيء", percentage: 20, count: 26 },
    { cause: "طلب منخفض", percentage: 12, count: 15 },
    { cause: "عطل ثلاجة", percentage: 5, count: 6 },
  ],
  warehouses: [
    { name: "مخزن تعز", wasteRate: 12.5, status: "خطر" },
    { name: "مخزن صنعاء", wasteRate: 3.2, status: "ممتاز" },
    { name: "مخزن عدن", wasteRate: 4.1, status: "جيد" },
  ],
  topWastedProducts: [
    { product: "عصير برتقال", wasteAmount: 450, unit: "زجاجة" },
    { product: "لبن شامي", wasteAmount: 320, unit: "علبة" },
    { product: "جبنة بيضاء", wasteAmount: 180, unit: "كيلو" },
  ],
};

// بيانات المرتجعات
export const returns = [
  {
    id: "RET-001",
    product: "عصير برتقال",
    branch: "فرع إب",
    returnDate: "2024-12-18",
    reason: "فساد",
    quantity: 25,
    predicted: true,
    predictionConfidence: 0.82,
    returnProbability: 0.85,
    predictedQuantity: 25,
    predictedReason: "Damage",
  },
  {
    id: "RET-002",
    product: "لبن شامي",
    branch: "فرع تعز",
    returnDate: "2024-12-19",
    reason: "انتهاء صلاحية",
    quantity: 15,
    predicted: false,
    predictionConfidence: 0.35,
    returnProbability: 0.30,
    predictedQuantity: 10,
    predictedReason: "Expiry",
  },
  {
    id: "RET-003",
    product: "دقيق",
    branch: "فرع عدن",
    returnDate: "2024-12-20",
    reason: "فائض مخزون",
    quantity: 50,
    predicted: true,
    predictionConfidence: 0.78,
    returnProbability: 0.72,
    predictedQuantity: 45,
    predictedReason: "Overstock",
  },
  {
    id: "RET-004",
    product: "سمن",
    branch: "فرع صنعاء",
    returnDate: "2024-12-21",
    reason: "تلف",
    quantity: 20,
    predicted: true,
    predictionConfidence: 0.88,
    returnProbability: 0.90,
    predictedQuantity: 22,
    predictedReason: "Damage",
  },
  {
    id: "RET-005",
    product: "زيت طبخ",
    branch: "فرع تعز",
    returnDate: "2024-12-22",
    reason: "انتهاء صلاحية",
    quantity: 30,
    predicted: true,
    predictionConfidence: 0.75,
    returnProbability: 0.68,
    predictedQuantity: 28,
    predictedReason: "Expiry",
  },
];

// بيانات الجمعيات الخيرية
export const charities = [
  {
    id: "CHAR-001",
    name: "جمعية البر الخيرية",
    contact: "0123456789",
    location: "صنعاء",
    status: "نشطة",
    totalDonations: 1250,
  },
  {
    id: "CHAR-002",
    name: "جمعية الإحسان",
    contact: "0987654321",
    location: "تعز",
    status: "نشطة",
    totalDonations: 890,
  },
];

// بيانات التبرعات المتاحة
export const availableDonations = [
  {
    batchId: "BATCH-002",
    productName: "عصير برتقال",
    quantity: 200,
    expiryDate: "2025-01-10",
    daysUntilExpiry: 21,
    location: "مخزن تعز",
    status: "متاح",
  },
];

// بيانات الإجراءات المقترحة
export const prescriptiveActions = [
  {
    title: "نقل منتج إلى مخزن آخر",
    description: "المنتج X معرض للهدر بنسبة 72%. ننصح بنقله إلى مخزن تعز خلال 48 ساعة لأن حركة البيع هناك أعلى بنسبة 40%.",
    priority: "high",
    location: "مخزن صنعاء",
    timestamp: "2024-12-20T10:00:00",
  },
  {
    title: "خفض كميات التعبئة",
    description: "دفعة من 'لبن شامي' ستنتهي بعد شهرين ولكن الطلب ضعيف في المكلا. يُنصح بخفض كميات التعبئة الجديدة.",
    priority: "medium",
    location: "مصنع الألبان",
    timestamp: "2024-12-20T09:30:00",
  },
  {
    title: "حملة تسويق محلية",
    description: "اقتراح حملة تسويق محلية للمنتجات القريبة من انتهاء الصلاحية في فرع إب.",
    priority: "medium",
    location: "فرع إب",
    timestamp: "2024-12-20T09:00:00",
  },
];

// بيانات التنبيهات
export const alerts = [
  {
    id: "ALT-001",
    type: "refrigeration",
    severity: "high",
    title: "ثلاجة FZ-14 في خطر",
    message: "الثلاجة FZ-14 قد تتعرض لعطل خلال 10 أيام",
    location: "مخزن تعز",
    timestamp: "2024-12-20T10:30:00",
  },
  {
    id: "ALT-002",
    type: "spoilage",
    severity: "high",
    title: "منتج معرض للفساد",
    message: "عصير برتقال (BATCH-002) معرض للفساد بنسبة 78%",
    location: "مخزن تعز",
    timestamp: "2024-12-20T09:15:00",
  },
  {
    id: "ALT-003",
    type: "expiry",
    severity: "medium",
    title: "منتج قريب من الانتهاء",
    message: "جبنة بيضاء (BATCH-003) ستنتهي خلال 18 يوم",
    location: "مخزن عدن",
    timestamp: "2024-12-20T08:00:00",
  },
];

// بيانات التوأم الرقمي
export const digitalTwinLocations = [
  {
    id: "LOC-001",
    name: "مخزن صنعاء الرئيسي",
    type: "warehouse",
    coordinates: { lat: 15.7000, lng: 43.6000 }, // Maximum distance North-West of Sana'a
    status: "normal", // normal, warning, critical
    capacity: 10000,
    currentStock: 7500,
    batches: 45,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:30:00",
  },
  {
    id: "LOC-002",
    name: "مخزن تعز",
    type: "warehouse",
    coordinates: { lat: 14.0000, lng: 43.4000 }, // Maximum distance North-West of Taiz
    status: "warning",
    capacity: 8000,
    currentStock: 7200,
    batches: 38,
    riskLevel: "medium",
    lastUpdate: "2025-01-15T10:25:00",
  },
  {
    id: "LOC-003",
    name: "مخزن عدن",
    type: "warehouse",
    coordinates: { lat: 13.4000, lng: 44.4000 }, // Maximum distance North-West of Aden
    status: "normal",
    capacity: 6000,
    currentStock: 4200,
    batches: 28,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:20:00",
  },
  {
    id: "LOC-004",
    name: "مصنع صنعاء",
    type: "factory",
    coordinates: { lat: 14.9000, lng: 44.6000 }, // Maximum distance South-East of Sana'a
    status: "normal",
    productionLines: 5,
    activeLines: 4,
    batches: 12,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:35:00",
  },
  {
    id: "LOC-005",
    name: "مصنع الحديدة",
    type: "factory",
    coordinates: { lat: 15.2000, lng: 42.3000 }, // Maximum distance North-West of Hodeidah
    status: "normal",
    productionLines: 3,
    activeLines: 3,
    batches: 8,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:28:00",
  },
  {
    id: "LOC-006",
    name: "فرع صنعاء - شارع الزبيري",
    type: "branch",
    coordinates: { lat: 15.2000, lng: 44.3500 }, // Center of Sana'a
    status: "normal",
    sales: 1250,
    stock: 850,
    batches: 15,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:15:00",
  },
  {
    id: "LOC-007",
    name: "فرع تعز - شارع جمال",
    type: "branch",
    coordinates: { lat: 13.3000, lng: 44.4000 }, // South-East of Taiz, maximum distance from warehouse
    status: "warning",
    sales: 980,
    stock: 620,
    batches: 12,
    riskLevel: "medium",
    lastUpdate: "2025-01-15T10:10:00",
  },
  {
    id: "LOC-008",
    name: "فرع عدن - شارع الجمهورية",
    type: "branch",
    coordinates: { lat: 12.4000, lng: 45.5000 }, // South-East of Aden, maximum distance from warehouse
    status: "normal",
    sales: 1450,
    stock: 920,
    batches: 18,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:05:00",
  },
  {
    id: "LOC-009",
    name: "فرع إب - شارع الثورة",
    type: "branch",
    coordinates: { lat: 13.9667, lng: 44.1667 },
    status: "normal",
    sales: 1100,
    stock: 750,
    batches: 10,
    riskLevel: "low",
    lastUpdate: "2025-01-15T10:00:00",
  },
  {
    id: "LOC-010",
    name: "فرع الحديدة - شارع البحر",
    type: "branch",
    coordinates: { lat: 14.5000, lng: 43.3000 }, // South-East of Hodeidah, maximum distance from factory
    status: "normal",
    sales: 1350,
    stock: 880,
    batches: 14,
    riskLevel: "low",
    lastUpdate: "2025-01-15T09:55:00",
  },
  {
    id: "LOC-011",
    name: "فرع ذمار - شارع السوق",
    type: "branch",
    coordinates: { lat: 14.5450, lng: 44.4056 },
    status: "normal",
    sales: 950,
    stock: 650,
    batches: 9,
    riskLevel: "low",
    lastUpdate: "2025-01-15T09:50:00",
  },
  {
    id: "LOC-012",
    name: "فرع المكلا - شارع النصر",
    type: "branch",
    coordinates: { lat: 14.5333, lng: 49.1333 },
    status: "normal",
    sales: 1200,
    stock: 800,
    batches: 11,
    riskLevel: "low",
    lastUpdate: "2025-01-15T09:45:00",
  },
  {
    id: "LOC-013",
    name: "فرع الحديدة - شارع الميناء",
    type: "branch",
    coordinates: { lat: 15.3000, lng: 42.4000 }, // North-West of Hodeidah, maximum distance from factory
    status: "normal",
    sales: 1300,
    stock: 900,
    batches: 13,
    riskLevel: "low",
    lastUpdate: "2025-01-15T09:40:00",
  },
];

// دفعات مع تتبع كامل للرحلة
// Helper function to get future dates
const getFutureDate = (daysFromNow) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

export const trackedBatches = [
  {
    id: "BATCH-2025-001",
    productName: "عصير برتقال",
    productId: "PROD-001",
    productionDate: getFutureDate(-30), // 30 days ago
    writtenExpiry: getFutureDate(45), // 45 days from now
    actualExpiry: getFutureDate(40), // 40 days from now (expires 5 days earlier)
    quantity: 500,
    currentLocation: "LOC-002",
    currentLocationName: "مخزن تعز",
    journey: [
      {
        location: "LOC-004",
        locationName: "مصنع صنعاء",
        action: "production",
        timestamp: `${getFutureDate(-30)}T08:00:00`,
        temperature: 22,
        humidity: 45,
      },
      {
        location: "LOC-001",
        locationName: "مخزن صنعاء الرئيسي",
        action: "storage",
        timestamp: `${getFutureDate(-30)}T14:30:00`,
        temperature: 4,
        humidity: 65,
        duration: "5 أيام",
      },
      {
        location: "LOC-002",
        locationName: "مخزن تعز",
        action: "transfer",
        timestamp: `${getFutureDate(-25)}T10:00:00`,
        temperature: 8,
        humidity: 70,
        duration: "9 أيام",
      },
    ],
    remainingLife: 40,
    riskLevel: "high",
    spoilageRisk: 78,
  },
  {
    id: "BATCH-2025-002",
    productName: "لبن شامي",
    productId: "PROD-002",
    productionDate: getFutureDate(-20), // 20 days ago
    writtenExpiry: getFutureDate(35), // 35 days from now
    actualExpiry: getFutureDate(38), // 38 days from now (expires 3 days later)
    quantity: 300,
    currentLocation: "LOC-001",
    currentLocationName: "مخزن صنعاء الرئيسي",
    journey: [
      {
        location: "LOC-004",
        locationName: "مصنع صنعاء",
        action: "production",
        timestamp: `${getFutureDate(-20)}T09:00:00`,
        temperature: 20,
        humidity: 50,
      },
      {
        location: "LOC-001",
        locationName: "مخزن صنعاء الرئيسي",
        action: "storage",
        timestamp: `${getFutureDate(-20)}T15:00:00`,
        temperature: 4,
        humidity: 60,
        duration: "5 أيام",
      },
    ],
    remainingLife: 38,
    riskLevel: "low",
    spoilageRisk: 12,
  },
  {
    id: "BATCH-2025-003",
    productName: "جبنة بيضاء",
    productId: "PROD-003",
    productionDate: getFutureDate(-15), // 15 days ago
    writtenExpiry: getFutureDate(30), // 30 days from now
    actualExpiry: getFutureDate(32), // 32 days from now (expires 2 days later)
    quantity: 200,
    currentLocation: "LOC-003",
    currentLocationName: "مخزن عدن",
    journey: [
      {
        location: "LOC-005",
        locationName: "مصنع الحديدة",
        action: "production",
        timestamp: `${getFutureDate(-15)}T07:00:00`,
        temperature: 18,
        humidity: 55,
      },
      {
        location: "LOC-003",
        locationName: "مخزن عدن",
        action: "storage",
        timestamp: `${getFutureDate(-15)}T13:00:00`,
        temperature: 5,
        humidity: 62,
        duration: "26 يوم",
      },
    ],
    remainingLife: 32,
    riskLevel: "low",
    spoilageRisk: 8,
  },
];

// تنبيهات مبكرة للدفعات
export const earlyWarnings = [
  {
    id: "EW-001",
    batchId: "BATCH-2025-001",
    productName: "عصير برتقال",
    daysUntilExpiry: 41,
    warningLevel: "60-days", // 60, 30, 15, 5
    message: "المنتج سينتهي خلال 41 يوم",
    location: "مخزن تعز",
    recommendedAction: "إعادة توزيع أو تبرع",
    priority: "high",
  },
  {
    id: "EW-002",
    batchId: "BATCH-2025-002",
    productName: "لبن شامي",
    daysUntilExpiry: 28,
    warningLevel: "30-days",
    message: "المنتج سينتهي خلال 28 يوم",
    location: "مخزن صنعاء الرئيسي",
    recommendedAction: "تسريع البيع أو تبرع",
    priority: "medium",
  },
  {
    id: "EW-003",
    batchId: "BATCH-2025-003",
    productName: "جبنة بيضاء",
    daysUntilExpiry: 21,
    warningLevel: "30-days",
    message: "المنتج سينتهي خلال 21 يوم",
    location: "مخزن عدن",
    recommendedAction: "تسريع البيع",
    priority: "medium",
  },
];

// بيانات إدارة الإنتاج
export const productionLines = [
  {
    id: "PL-001",
    name: "خط إنتاج الألبان 1",
    factory: "مصنع صنعاء",
    status: "active", // active, idle, maintenance
    currentProduct: "لبن شامي",
    productionRate: 120, // units/hour
    efficiency: 95,
    scheduledHours: 16,
    completedHours: 8,
    qualityScore: 98,
    lastMaintenance: "2025-01-10",
    nextMaintenance: "2025-02-10",
  },
  {
    id: "PL-002",
    name: "خط إنتاج الألبان 2",
    factory: "مصنع صنعاء",
    status: "active",
    currentProduct: "جبنة بيضاء",
    productionRate: 100,
    efficiency: 92,
    scheduledHours: 16,
    completedHours: 6,
    qualityScore: 96,
    lastMaintenance: "2025-01-08",
    nextMaintenance: "2025-02-08",
  },
  {
    id: "PL-003",
    name: "خط إنتاج العصائر 1",
    factory: "مصنع صنعاء",
    status: "active",
    currentProduct: "عصير برتقال",
    productionRate: 200,
    efficiency: 88,
    scheduledHours: 12,
    completedHours: 4,
    qualityScore: 94,
    lastMaintenance: "2025-01-12",
    nextMaintenance: "2025-02-12",
  },
  {
    id: "PL-004",
    name: "خط إنتاج العصائر 2",
    factory: "مصنع الحديدة",
    status: "idle",
    currentProduct: null,
    productionRate: 0,
    efficiency: 0,
    scheduledHours: 0,
    completedHours: 0,
    qualityScore: 0,
    lastMaintenance: "2025-01-05",
    nextMaintenance: "2025-02-05",
  },
  {
    id: "PL-005",
    name: "خط إنتاج المعلبات 1",
    factory: "مصنع الحديدة",
    status: "maintenance",
    currentProduct: null,
    productionRate: 0,
    efficiency: 0,
    scheduledHours: 0,
    completedHours: 0,
    qualityScore: 0,
    lastMaintenance: "2025-01-15",
    nextMaintenance: "2025-01-20",
  },
];

export const productionSchedule = [
  {
    id: "SCH-001",
    product: "لبن شامي",
    productionLine: "PL-001",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-16",
    startTime: "06:00",
    endTime: "22:00",
    quantity: 1920, // units
    priority: "high",
    status: "in-progress", // scheduled, in-progress, completed, cancelled
    governorate: "صنعاء",
    demandForecast: 850,
    actualProduction: 960,
    completion: 50,
  },
  {
    id: "SCH-002",
    product: "جبنة بيضاء",
    productionLine: "PL-002",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-16",
    startTime: "08:00",
    endTime: "24:00",
    quantity: 1600,
    priority: "medium",
    status: "in-progress",
    governorate: "عدن",
    demandForecast: 450,
    actualProduction: 600,
    completion: 37.5,
  },
  {
    id: "SCH-003",
    product: "عصير برتقال",
    productionLine: "PL-003",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-16",
    startTime: "10:00",
    endTime: "22:00",
    quantity: 2400,
    priority: "high",
    status: "in-progress",
    governorate: "تعز",
    demandForecast: 620,
    actualProduction: 800,
    completion: 33.3,
  },
  {
    id: "SCH-004",
    product: "لبن شامي",
    productionLine: "PL-001",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-17",
    startTime: "06:00",
    endTime: "22:00",
    quantity: 1920,
    priority: "high",
    status: "scheduled",
    governorate: "إب",
    demandForecast: 380,
    actualProduction: 0,
    completion: 0,
  },
  {
    id: "SCH-005",
    product: "عصير تفاح",
    productionLine: "PL-003",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-17",
    startTime: "08:00",
    endTime: "20:00",
    quantity: 1800,
    priority: "medium",
    status: "scheduled",
    governorate: "المكلا",
    demandForecast: 290,
    actualProduction: 0,
    completion: 0,
  },
  {
    id: "SCH-006",
    product: "جبنة بيضاء",
    productionLine: "PL-002",
    factory: "مصنع صنعاء",
    scheduledDate: "2025-01-18",
    startTime: "06:00",
    endTime: "22:00",
    quantity: 1920,
    priority: "high",
    status: "scheduled",
    governorate: "صنعاء",
    demandForecast: 750,
    actualProduction: 0,
    completion: 0,
  },
];

// بيانات الإنتاج المثالي (لنموذج Optimal Production Quantity)
export const optimalProductionData = [
  {
    product: "دقيق",
    productId: "PROD-001",
    demandForecast: 850,
    currentStock: 120,
    optimalQuantity: 780,
    expectedWaste: 45,
    confidence: 0.85,
    recommendation: "Proceed",
  },
  {
    product: "سمن",
    productId: "PROD-002",
    demandForecast: 450,
    currentStock: 80,
    optimalQuantity: 420,
    expectedWaste: 25,
    confidence: 0.78,
    recommendation: "Proceed",
  },
  {
    product: "زيت طبخ",
    productId: "PROD-003",
    demandForecast: 620,
    currentStock: 150,
    optimalQuantity: 520,
    expectedWaste: 35,
    confidence: 0.82,
    recommendation: "Proceed",
  },
  {
    product: "معجون طماطم",
    productId: "PROD-004",
    demandForecast: 380,
    currentStock: 60,
    optimalQuantity: 360,
    expectedWaste: 20,
    confidence: 0.75,
    recommendation: "Proceed",
  },
  {
    product: "شوربة",
    productId: "PROD-005",
    demandForecast: 290,
    currentStock: 40,
    optimalQuantity: 280,
    expectedWaste: 15,
    confidence: 0.80,
    recommendation: "Proceed",
  },
  {
    product: "فيمتو",
    productId: "PROD-006",
    demandForecast: 750,
    currentStock: 200,
    optimalQuantity: 600,
    expectedWaste: 50,
    confidence: 0.88,
    recommendation: "Proceed",
  },
];

export const productionRecommendations = [
  {
    id: "REC-001",
    type: "optimization",
    title: "تحسين جدول الإنتاج",
    description: "يمكن تحسين جدول الإنتاج لخط PL-001 عن طريق زيادة ساعات العمل لتلبية الطلب المتوقع",
    impact: "high",
    priority: "high",
    estimatedSavings: 15000,
    action: "زيادة ساعات الإنتاج",
  },
  {
    id: "REC-002",
    type: "maintenance",
    title: "صيانة وقائية",
    description: "خط PL-005 يحتاج إلى صيانة وقائية قبل استئناف الإنتاج",
    impact: "medium",
    priority: "high",
    estimatedSavings: 5000,
    action: "جدولة الصيانة",
  },
  {
    id: "REC-003",
    type: "demand",
    title: "تعديل الكمية المخططة",
    description: "الطلب المتوقع لمنتج 'عصير برتقال' في تعز أقل من الكمية المخططة. تقليل الكمية لتجنب الهدر",
    impact: "high",
    priority: "medium",
    estimatedSavings: 8000,
    action: "تعديل الكمية",
  },
];

